- name: Status server
  hosts: webserver
  become: yes
  tasks:
    
    - name: Update and Upgrade
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: Record start time
      command: date +%s
      register: start_time

    - name: copy script status_server
      copy:
        src: status.py
        dest: /home/{{ ansible_user }}

    - name: install pip
      apt:
        name: python3-pip
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: install package psutil, ping3 
      pip:
        name: "{{item}}"
        state: present
      loop: ['psutil', 'ping3']
     
    - name: exceute script python
      command: python3 /home/{{ ansible_user }}/status.py
    
    - name: Obtener el hostname del servidor
      command: hostname
      register: hostname_resul
    
    - name: copy arch server init
      command: scp /home/{{ ansible_user }}/{{ hostname_resul.stdout }}_status.txt dev@{{ Server_dest }}:{{ url_server }}
    
    - name: Record end time
      command: date +%s
      register: end_time

    - name: Calculate elapsed time
      set_fact:
        elapsed_time: "{{ (end_time.stdout | int) - (start_time.stdout | int) }}"

    - name: Show elapsed time
      debug:
        msg: "Playbook execution time: {{ elapsed_time }} seconds"