---
- name: Install nginx
  hosts: webserver
  become: true
  vars_files:
    - vars.yml  # Este archivo contiene la variable repo_nginx
  tasks:
    - name: Add repository de Nginx
      apt_repository:
        repo: "{{ url_nginx }} {{ ansible_lsb.codename }} nginx"
        filename: "nginx"
        state: present
